export const PERMISSIONS = {
    REQUISITION_CREATE: "REQUISITION.CREATE",
    REQUISITION_VIEW: "REQUISITION.VIEW",
    REQUISITION_EDIT: "REQUISITION.EDIT",
    REQUISITION_DELETE: "REQUISITION.DELETE",

    REQUISITION_APPROVE: "REQUISITION.APPROVE",
    REQUISITION_REJECT: "REQUISITION.REJECT",

    BUDGET_VIEW: "BUDGET.VIEW",
    BUDGET_LOCK: "BUDGET.LOCK",
    BUDGET_RELEASE: "BUDGET.RELEASE",

    INTERVIEW_SCHEDULE: "INTERVIEW.SCHEDULE",
    INTERVIEW_BYPASS: "INTERVIEW.BYPASS",

    CANDIDATE_VIEW: "CANDIDATE.VIEW",
    CANDIDATE_UNMASK: "CANDIDATE.UNMASK",

    VENDOR_VIEW: "VENDOR.VIEW",

    USER_MANAGE: "USER.MANAGE",

    ROLE_MANAGE: "ROLE.MANAGE",

    SECURITY_FAILED_LOGINS_VIEW: "SECURITY.FAILED_LOGINS.VIEW",
    SECURITY_SESSIONS_REVOKE: "SECURITY.SESSIONS.REVOKE",
    SECURITY_EVENTS_EXPORT: "SECURITY.EVENTS.EXPORT",
    SECURITY_ADMIN: "SECURITY.ADMIN",
    SECURITY_USERS_FORCE_LOGOUT: "SECURITY.USERS.FORCE_LOGOUT",
    SECURITY_DASHBOARD_VIEW: "SECURITY.DASHBOARD.VIEW",
    SECURITY_EVENTS_VIEW: "SECURITY.EVENTS.VIEW",
    SECURITY_SESSIONS_VIEW: "SECURITY.SESSIONS.VIEW",
} as const;