export const ROLES = {
    REQUESTOR: "REQUESTOR",

    INTERVIEWER: "INTERVIEWER",

    MAIN_INTERVIEWER: "MAIN_INTERVIEWER",

    LINE_MANAGER: "LINE_MANAGER",

    WORK_COMPLETION_ASSIGNEE:
        "WORK_COMPLETION_ASSIGNEE",

    HOD: "HOD",

    HR: "HR",

    FINANCE: "FINANCE",

    PROCUREMENT: "PROCUREMENT",

    VENDOR: "VENDOR",

    SYSTEM_ADMIN: "SYSTEM_ADMIN",
} as const;