export const SECURITY_EVENTS = {
    // --- Authentication & Sessions ---
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",
    FORCE_LOGOUT: "FORCE_LOGOUT",
    SESSION_CREATED: "SESSION_CREATED",
    SESSION_REVOKED: "SESSION_REVOKED",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    FINGERPRINT_MISMATCH: "FINGERPRINT_MISMATCH",

    // --- Account Management ---
    ACCOUNT_CREATED: "ACCOUNT_CREATED",
    ACCOUNT_DELETED: "ACCOUNT_DELETED",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    ACCOUNT_UNLOCKED: "ACCOUNT_UNLOCKED",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    ACCOUNT_ENABLED: "ACCOUNT_ENABLED",

    // --- Tokens ---
    REFRESH_TOKEN_CREATED: "REFRESH_TOKEN_CREATED",
    REFRESH_TOKEN_ROTATED: "REFRESH_TOKEN_ROTATED",
    REFRESH_TOKEN_REPLAY: "REFRESH_TOKEN_REPLAY",
    REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",

    // --- Credentials & Passwords ---
    PASSWORD_CHANGED: "PASSWORD_CHANGED",
    PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
    PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
    PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",

    // --- Multi-Factor Authentication (MFA) ---
    MFA_ENABLED: "MFA_ENABLED",
    MFA_DISABLED: "MFA_DISABLED",
    MFA_VERIFIED: "MFA_VERIFIED",
    MFA_FAILED: "MFA_FAILED",

    // --- Access & Authorization ---
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    ROLE_CHANGED: "ROLE_CHANGED",
    PERMISSION_CHANGED: "PERMISSION_CHANGED",

    // --- API & Integration ---
    API_KEY_GENERATED: "API_KEY_GENERATED",
    API_KEY_REVOKED: "API_KEY_REVOKED",

} as const;